### ISSUE TITLE
Feature to remove profiles

### ISSUE THREAD

**Issue by kaiyalith** [S87GMIL/e621Configurator#2]
Importing/Exporting is nice and all, but over time the mass amount of user-created profiles can clutter the view or this would be useful if user wants to no longer have some profile they created

**Comment by S87GMIL** [comment]
Sorry, must have missed the suggestion.
That's a good point, I will implement it.
Thanks :)

**Comment by S87GMIL** [comment]
I just noticed, that it is already possible.
The only exception being the default "e621" profile and the "s87 tweaks" profile, because these are considered "essential":
![image](https://user-images.githubusercontent.com/63162984/211204103-a004d117-a1c1-4b97-9fed-f06657d6742e.png)
